# Generated by Django 5.0.6 on 2025-06-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_complaint_file_complaint_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Filed', 'Filed'), ('In progress', 'In Progress'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Filed', max_length=20),
        ),
    ]
